### ISSUE TITLE
Error in firebase.mlkit.recognizeTextCloud: TypeError: Cannot read property 'android' of undefined

### ISSUE THREAD

**Issue by BaronChen** [EddyVerbruggen/nativescript-plugin-firebase#921]
Hi there,

When running the following code 
```
onTextExtract() {
		firebase.mlkit.textrecognition.recognizeTextCloud({
			image: this.imageTaken, // a NativeScript Image or ImageSource, see the demo for examples
		})
		.then((result: MLKitRecognizeTextResult) => {
    	this.blocks = result.blocks;
		})
		.catch(errorMessage => console.log("ML Kit error: " + errorMessage));
	}
```

I am getting an error in the console log:

```
JS: Error in firebase.mlkit.recognizeTextCloud: TypeError: Cannot read property 'android' of undefined
JS: ML Kit error: TypeError: Cannot read property 'android' of undefined
```

I think the error come from src/mlkit/textrecognition/index.android.ts: 106 (come.google is undefined in com.google.android.gms.tasks.OnSuccessListener).

Thank you very much for you help.

**Comment by BaronChen** [comment]
Solved by remove another plugin.

**Comment by henriquecf** [comment]
Hello @BaronChen I am having the same issue. What did you do to solve this? I have tested this in a blank project it gives me the same error, using therecognizeTextOnDevice instead...

**Comment by VACKOM** [comment]
Hello @BaronChen  I am also having the same issue here. Which plugin did you remove to solve this issue?

**Comment by MPerezMateo** [comment]
Me too. Please report if you found the plugin interfering with this issue

**Comment by Friends-School-Development** [comment]
This response is pretty late and you have probably already found an answer, but here's something that could help others who encounter the same issue. I did not solve the issue by removing another plugin. The property 'android' is actually part of NativeScript ImageSource, so this was probably set up incorrectly. Here is how to set it up correctly with TypeScript. First, you need to import ImageSource:
`import { ImageSource, fromFile } from "tns-core-modules/image-source";`

Next, set your ImageSource to whatever image you want to scan using the firebase recognize text. This is just the path that I have for my project so this will look different for yours.
`let localImage: ImageSource = fromFile('~/assets/image/image.jpg');`

And then put it into the text recognize method. Here's what mine looks like for reference:
`private runTextRecognition(){
  let localImage: ImageSource = fromFile('~/assets/image/scorecard1.jpg');

  this.firebase.mlkit.textrecognition.recognizeTextOnDevice({
  image: localImage 
                     }).then((result: MLKitRecognizeTextResult) => {
  console.log(result.text ? result.text : "");
     }).catch(errorMessage => console.log("ML Kit error: " + errorMessage));

}`

**Comment by hgeller02** [comment]
This response is pretty late and you have probably already found an answer, but here's something that could help others who encounter the same issue. I did not solve the issue by removing another plugin. The property 'android' is actually part of NativeScript ImageSource, so this was probably set up incorrectly. Here is how to set it up correctly with TypeScript. First, you need to import ImageSource:
`import { ImageSource, fromFile } from "tns-core-modules/image-source";`

Next, set your ImageSource to whatever image you want to scan using the firebase recognize text. This is just the path that I have for my project so this will look different for yours.
`let localImage: ImageSource = fromFile('~/assets/image/image.jpg');`

And then put it into the text recognize method. Here's what mine looks like for reference:
`private runTextRecognition(){
let localImage: ImageSource = fromFile('~/assets/image/scorecard1.jpg');

this.firebase.mlkit.textrecognition.recognizeTextOnDevice({
image: localImage
}).then((result: MLKitRecognizeTextResult) => {
console.log(result.text ? result.text : "");
}).catch(errorMessage => console.log("ML Kit error: " + errorMessage));

}`
